/*
 
    Copyright IBM Corp. 2012, 2016
    This file is part of Anomaly Detection Engine for Linux Logs (ADE).

    ADE is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ADE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with ADE.  If not, see <http://www.gnu.org/licenses/>.
 
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.28 at 03:43:40 AM EDT 
//

package org.openmainframe.ade.ext.xml.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>Java class for interval_message_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="interval_message_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="num_instances" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bernoulli">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
 *                 &lt;attribute name="frequency" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cluster_id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="periodicity">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="status" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="IN_SYNC"/>
 *                       &lt;enumeration value="NOT_IN_SYNC"/>
 *                       &lt;enumeration value="NOT_PERIODIC"/>
 *                       &lt;enumeration value="NEW"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="last_issued" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="poisson">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
 *                 &lt;attribute name="mean" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="intCont" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="normIntCont" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="anomaly" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="cluster_status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="critical_words" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="text_sum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="text_smp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="time_vec" type="{http://www.openmainframe.org/ade/AdeCoreIntervalV2}interval_time_vector_type"/>
 *         &lt;element name="active_rules" type="{http://www.openmainframe.org/ade/AdeCoreIntervalV2}active_rules_type" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="msg_id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "interval_message_type", namespace = "http://www.openmainframe.org/ade/AdeCoreIntervalV2", propOrder = {
        "numInstances",
        "bernoulli",
        "clusterId",
        "periodicity",
        "poisson",
        "intCont",
        "normIntCont",
        "anomaly",
        "clusterStatus",
        "criticalWords",
        "textSum",
        "textSmp",
        "timeVec",
        "activeRules"
})
public class IntervalMessageType {

    @XmlElement(name = "num_instances", namespace = "http://www.openmainframe.org/ade/AdeCoreIntervalV2")
    protected int numInstances;
    @XmlElement(namespace = "http://www.openmainframe.org/ade/AdeCoreIntervalV2", required = true)
    protected IntervalMessageType.Bernoulli bernoulli;
    @XmlElement(name = "cluster_id", namespace = "http://www.openmainframe.org/ade/AdeCoreIntervalV2")
    protected int clusterId;
    @XmlElement(namespace = "http://www.openmainframe.org/ade/AdeCoreIntervalV2", required = true)
    protected IntervalMessageType.Periodicity periodicity;
    @XmlElement(namespace = "http://www.openmainframe.org/ade/AdeCoreIntervalV2", required = true)
    protected IntervalMessageType.Poisson poisson;
    @XmlElement(namespace = "http://www.openmainframe.org/ade/AdeCoreIntervalV2")
    protected double intCont;
    @XmlElement(namespace = "http://www.openmainframe.org/ade/AdeCoreIntervalV2")
    protected double normIntCont;
    @XmlElement(namespace = "http://www.openmainframe.org/ade/AdeCoreIntervalV2")
    protected double anomaly;
    @XmlElement(name = "cluster_status", namespace = "http://www.openmainframe.org/ade/AdeCoreIntervalV2", required = true)
    protected String clusterStatus;
    @XmlElement(name = "critical_words", namespace = "http://www.openmainframe.org/ade/AdeCoreIntervalV2")
    protected double criticalWords;
    @XmlElement(name = "text_sum", namespace = "http://www.openmainframe.org/ade/AdeCoreIntervalV2", required = true)
    protected String textSum;
    @XmlElement(name = "text_smp", namespace = "http://www.openmainframe.org/ade/AdeCoreIntervalV2", required = true)
    protected String textSmp;
    @XmlElement(name = "time_vec", namespace = "http://www.openmainframe.org/ade/AdeCoreIntervalV2", required = true)
    protected IntervalTimeVectorType timeVec;
    @XmlElement(name = "active_rules", namespace = "http://www.openmainframe.org/ade/AdeCoreIntervalV2")
    protected ActiveRulesType activeRules;
    @XmlAttribute(name = "msg_id", required = true)
    protected String msgId;

    /**
     * Gets the value of the numInstances property.
     * 
     */
    public final int getNumInstances() {
        return numInstances;
    }

    /**
     * Sets the value of the numInstances property.
     * 
     */
    public final void setNumInstances(int value) {
        this.numInstances = value;
    }

    /**
     * Gets the value of the bernoulli property.
     * 
     * @return
     *     possible object is
     *     {@link IntervalMessageType.Bernoulli }
     *     
     */
    public final IntervalMessageType.Bernoulli getBernoulli() {
        return bernoulli;
    }

    /**
     * Sets the value of the bernoulli property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntervalMessageType.Bernoulli }
     *     
     */
    public final void setBernoulli(IntervalMessageType.Bernoulli value) {
        this.bernoulli = value;
    }

    /**
     * Gets the value of the clusterId property.
     * 
     */
    public final int getClusterId() {
        return clusterId;
    }

    /**
     * Sets the value of the clusterId property.
     * 
     */
    public final void setClusterId(int value) {
        this.clusterId = value;
    }

    /**
     * Gets the value of the periodicity property.
     * 
     * @return
     *     possible object is
     *     {@link IntervalMessageType.Periodicity }
     *     
     */
    public final IntervalMessageType.Periodicity getPeriodicity() {
        return periodicity;
    }

    /**
     * Sets the value of the periodicity property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntervalMessageType.Periodicity }
     *     
     */
    public final void setPeriodicity(IntervalMessageType.Periodicity value) {
        this.periodicity = value;
    }

    /**
     * Gets the value of the poisson property.
     * 
     * @return
     *     possible object is
     *     {@link IntervalMessageType.Poisson }
     *     
     */
    public final IntervalMessageType.Poisson getPoisson() {
        return poisson;
    }

    /**
     * Sets the value of the poisson property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntervalMessageType.Poisson }
     *     
     */
    public final void setPoisson(IntervalMessageType.Poisson value) {
        this.poisson = value;
    }

    /**
     * Gets the value of the intCont property.
     * 
     */
    public final double getIntCont() {
        return intCont;
    }

    /**
     * Sets the value of the intCont property.
     * 
     */
    public final void setIntCont(double value) {
        this.intCont = value;
    }

    /**
     * Gets the value of the normIntCont property.
     * 
     */
    public final double getNormIntCont() {
        return normIntCont;
    }

    /**
     * Sets the value of the normIntCont property.
     * 
     */
    public final void setNormIntCont(double value) {
        this.normIntCont = value;
    }

    /**
     * Gets the value of the anomaly property.
     * 
     */
    public final double getAnomaly() {
        return anomaly;
    }

    /**
     * Sets the value of the anomaly property.
     * 
     */
    public final void setAnomaly(double value) {
        this.anomaly = value;
    }

    /**
     * Gets the value of the clusterStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public final String getClusterStatus() {
        return clusterStatus;
    }

    /**
     * Sets the value of the clusterStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public final void setClusterStatus(String value) {
        this.clusterStatus = value;
    }

    /**
     * Gets the value of the criticalWords property.
     * 
     */
    public final double getCriticalWords() {
        return criticalWords;
    }

    /**
     * Sets the value of the criticalWords property.
     * 
     */
    public final void setCriticalWords(double value) {
        this.criticalWords = value;
    }

    /**
     * Gets the value of the textSum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public final String getTextSum() {
        return textSum;
    }

    /**
     * Sets the value of the textSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public final void setTextSum(String value) {
        this.textSum = value;
    }

    /**
     * Gets the value of the textSmp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public final String getTextSmp() {
        return textSmp;
    }

    /**
     * Sets the value of the textSmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public final void setTextSmp(String value) {
        this.textSmp = value;
    }

    /**
     * Gets the value of the timeVec property.
     * 
     * @return
     *     possible object is
     *     {@link IntervalTimeVectorType }
     *     
     */
    public final IntervalTimeVectorType getTimeVec() {
        return timeVec;
    }

    /**
     * Sets the value of the timeVec property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntervalTimeVectorType }
     *     
     */
    public final void setTimeVec(IntervalTimeVectorType value) {
        this.timeVec = value;
    }

    /**
     * Gets the value of the activeRules property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveRulesType }
     *     
     */
    public final ActiveRulesType getActiveRules() {
        return activeRules;
    }

    /**
     * Sets the value of the activeRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveRulesType }
     *     
     */
    public final void setActiveRules(ActiveRulesType value) {
        this.activeRules = value;
    }

    /**
     * Gets the value of the msgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public final String getMsgId() {
        return msgId;
    }

    /**
     * Sets the value of the msgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public final void setMsgId(String value) {
        this.msgId = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
     *       &lt;attribute name="frequency" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class Bernoulli {

        @XmlValue
        protected double value;
        @XmlAttribute(name = "frequency", required = true)
        protected double frequency;

        /**
         * Gets the value of the value property.
         * 
         */
        public final double getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public final void setValue(double value) {
            this.value = value;
        }

        /**
         * Gets the value of the frequency property.
         * 
         */
        public final double getFrequency() {
            return frequency;
        }

        /**
         * Sets the value of the frequency property.
         * 
         */
        public final void setFrequency(double value) {
            this.frequency = value;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="status" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="IN_SYNC"/>
     *             &lt;enumeration value="NOT_IN_SYNC"/>
     *             &lt;enumeration value="NOT_PERIODIC"/>
     *             &lt;enumeration value="NEW"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="last_issued" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="score" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Periodicity {

        @XmlAttribute(name = "status", required = true)
        protected String status;
        @XmlAttribute(name = "last_issued")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar lastIssued;
        @XmlAttribute(name = "score")
        protected Double score;

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public final String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public final void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the lastIssued property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public final XMLGregorianCalendar getLastIssued() {
            return lastIssued;
        }

        /**
         * Sets the value of the lastIssued property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public final void setLastIssued(XMLGregorianCalendar value) {
            this.lastIssued = value;
        }

        /**
         * Gets the value of the score property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public final Double getScore() {
            return score;
        }

        /**
         * Sets the value of the score property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public final void setScore(Double value) {
            this.score = value;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>double">
     *       &lt;attribute name="mean" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class Poisson {

        @XmlValue
        protected double value;
        @XmlAttribute(name = "mean", required = true)
        protected double mean;

        /**
         * Gets the value of the value property.
         * 
         */
        public final double getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public final void setValue(double value) {
            this.value = value;
        }

        /**
         * Gets the value of the mean property.
         * 
         */
        public final double getMean() {
            return mean;
        }

        /**
         * Sets the value of the mean property.
         * 
         */
        public final void setMean(double value) {
            this.mean = value;
        }

    }

}
