/*
 
    Copyright IBM Corp. 2012, 2016
    This file is part of Anomaly Detection Engine for Linux Logs (ADE).

    ADE is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ADE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with ADE.  If not, see <http://www.gnu.org/licenses/>.
 
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.28 at 03:44:07 AM EDT 
//

package org.openmainframe.ade.ext.xml.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="start_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="end_time" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="gmt_offset" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="number_intervals">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
 *                 &lt;attribute name="analysis_snapshot_size" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="interval_size" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="model_info">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="model_creation_date" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *                 &lt;attribute name="training_period" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="analysis_group" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="system" type="{http://www.openmainframe.org/ade/AdeCorePlexV2}systems_system_type"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "version",
        "startTime",
        "endTime",
        "gmtOffset",
        "numberIntervals",
        "intervalSize",
        "modelInfo",
        "system"
})
@XmlRootElement(name = "systems", namespace = "http://www.openmainframe.org/ade/AdeCorePlexV2")
public class Systems {

    @XmlElement(namespace = "http://www.openmainframe.org/ade/AdeCorePlexV2")
    protected int version;
    @XmlElement(name = "start_time", namespace = "http://www.openmainframe.org/ade/AdeCorePlexV2", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTime;
    @XmlElement(name = "end_time", namespace = "http://www.openmainframe.org/ade/AdeCorePlexV2", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endTime;
    @XmlElement(name = "gmt_offset", namespace = "http://www.openmainframe.org/ade/AdeCorePlexV2", required = true)
    protected String gmtOffset;
    @XmlElement(name = "number_intervals", namespace = "http://www.openmainframe.org/ade/AdeCorePlexV2", required = true)
    protected Systems.NumberIntervals numberIntervals;
    @XmlElement(name = "interval_size", namespace = "http://www.openmainframe.org/ade/AdeCorePlexV2")
    protected int intervalSize;
    @XmlElement(name = "model_info", namespace = "http://www.openmainframe.org/ade/AdeCorePlexV2", required = true)
    protected Systems.ModelInfo modelInfo;
    @XmlElement(namespace = "http://www.openmainframe.org/ade/AdeCorePlexV2", required = true)
    protected SystemsSystemType system;

    /**
     * Gets the value of the version property.
     * 
     */
    public final int getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public final void setVersion(int value) {
        this.version = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public final XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public final void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public final XMLGregorianCalendar getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public final void setEndTime(XMLGregorianCalendar value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the gmtOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public final String getGmtOffset() {
        return gmtOffset;
    }

    /**
     * Sets the value of the gmtOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public final void setGmtOffset(String value) {
        this.gmtOffset = value;
    }

    /**
     * Gets the value of the numberIntervals property.
     * 
     * @return
     *     possible object is
     *     {@link Systems.NumberIntervals }
     *     
     */
    public final Systems.NumberIntervals getNumberIntervals() {
        return numberIntervals;
    }

    /**
     * Sets the value of the numberIntervals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Systems.NumberIntervals }
     *     
     */
    public final void setNumberIntervals(Systems.NumberIntervals value) {
        this.numberIntervals = value;
    }

    /**
     * Gets the value of the intervalSize property.
     * 
     */
    public final int getIntervalSize() {
        return intervalSize;
    }

    /**
     * Sets the value of the intervalSize property.
     * 
     */
    public final void setIntervalSize(int value) {
        this.intervalSize = value;
    }

    /**
     * Gets the value of the modelInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Systems.ModelInfo }
     *     
     */
    public final Systems.ModelInfo getModelInfo() {
        return modelInfo;
    }

    /**
     * Sets the value of the modelInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Systems.ModelInfo }
     *     
     */
    public final void setModelInfo(Systems.ModelInfo value) {
        this.modelInfo = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link SystemsSystemType }
     *     
     */
    public final SystemsSystemType getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemsSystemType }
     *     
     */
    public final void setSystem(SystemsSystemType value) {
        this.system = value;
    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="model_creation_date" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
     *       &lt;attribute name="training_period" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="analysis_group" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ModelInfo {

        @XmlAttribute(name = "model_creation_date", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar modelCreationDate;
        @XmlAttribute(name = "training_period", required = true)
        protected int trainingPeriod;
        @XmlAttribute(name = "analysis_group", required = true)
        protected String analysisGroup;

        /**
         * Gets the value of the modelCreationDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public final XMLGregorianCalendar getModelCreationDate() {
            return modelCreationDate;
        }

        /**
         * Sets the value of the modelCreationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public final void setModelCreationDate(XMLGregorianCalendar value) {
            this.modelCreationDate = value;
        }

        /**
         * Gets the value of the trainingPeriod property.
         * 
         */
        public final int getTrainingPeriod() {
            return trainingPeriod;
        }

        /**
         * Sets the value of the trainingPeriod property.
         * 
         */
        public final void setTrainingPeriod(int value) {
            this.trainingPeriod = value;
        }

        /**
         * Gets the value of the analysisGroup property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public final String getAnalysisGroup() {
            return analysisGroup;
        }

        /**
         * Sets the value of the analysisGroup property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public final void setAnalysisGroup(String value) {
            this.analysisGroup = value;
        }

    }

    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
     *       &lt;attribute name="analysis_snapshot_size" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "value"
    })
    public static class NumberIntervals {

        @XmlValue
        protected int value;
        @XmlAttribute(name = "analysis_snapshot_size", required = true)
        protected int analysisSnapshotSize;

        /**
         * Gets the value of the value property.
         * 
         */
        public final int getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public final void setValue(int value) {
            this.value = value;
        }

        /**
         * Gets the value of the analysisSnapshotSize property.
         * 
         */
        public final int getAnalysisSnapshotSize() {
            return analysisSnapshotSize;
        }

        /**
         * Sets the value of the analysisSnapshotSize property.
         * 
         */
        public final void setAnalysisSnapshotSize(int value) {
            this.analysisSnapshotSize = value;
        }

    }

}
