/*
 
    Copyright IBM Corp. 2012, 2016
    This file is part of Anomaly Detection Engine for Linux Logs (ADE).

    ADE is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ADE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with ADE.  If not, see <http://www.gnu.org/licenses/>.
 
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.03.24 at 01:06:14 PM EDT
//

package org.openmainframe.ade.ext.xml.v2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for systems_interval_type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="systems_interval_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="num_unique_msg_ids" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="anomaly_score" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *       &lt;attribute name="num_never_seen_before_messages" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="num_new_messages" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="index" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="missing" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="missing_reason" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="limited_model">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Yes"/>
 *             &lt;enumeration value="No"/>
 *             &lt;enumeration value="Unknown"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "systems_interval_type", namespace = "http://www.openmainframe.org/ade/AdeCorePlexV2", propOrder = {
        "numUniqueMsgIds",
        "anomalyScore"
})
public class SystemsIntervalType {

    @XmlElement(name = "num_unique_msg_ids", namespace = "http://www.openmainframe.org/ade/AdeCorePlexV2")
    protected int numUniqueMsgIds;
    @XmlElement(name = "anomaly_score", namespace = "http://www.openmainframe.org/ade/AdeCorePlexV2")
    protected double anomalyScore;
    @XmlAttribute(name = "num_never_seen_before_messages", required = true)
    protected int numNeverSeenBeforeMessages;
    @XmlAttribute(name = "num_new_messages", required = true)
    protected int numNewMessages;
    @XmlAttribute(name = "index", required = true)
    protected int index;
    @XmlAttribute(name = "missing", required = true)
    protected boolean missing;
    @XmlAttribute(name = "missing_reason")
    protected String missingReason;
    @XmlAttribute(name = "limited_model")
    protected String limitedModel;

    /**
     * Gets the value of the numUniqueMsgIds property.
     *
     */
    public final int getNumUniqueMsgIds() {
        return numUniqueMsgIds;
    }

    /**
     * Sets the value of the numUniqueMsgIds property.
     *
     */
    public final void setNumUniqueMsgIds(int value) {
        this.numUniqueMsgIds = value;
    }

    /**
     * Gets the value of the anomalyScore property.
     *
     */
    public final double getAnomalyScore() {
        return anomalyScore;
    }

    /**
     * Sets the value of the anomalyScore property.
     *
     */
    public final void setAnomalyScore(double value) {
        this.anomalyScore = value;
    }

    /**
     * Gets the value of the numNeverSeenBeforeMessages property.
     *
     */
    public final int getNumNeverSeenBeforeMessages() {
        return numNeverSeenBeforeMessages;
    }

    /**
     * Sets the value of the numNeverSeenBeforeMessages property.
     *
     */
    public final void setNumNeverSeenBeforeMessages(int value) {
        this.numNeverSeenBeforeMessages = value;
    }

    /**
     * Gets the value of the numNewMessages property.
     *
     */
    public final int getNumNewMessages() {
        return numNewMessages;
    }

    /**
     * Sets the value of the numNewMessages property.
     *
     */
    public final void setNumNewMessages(int value) {
        this.numNewMessages = value;
    }

    /**
     * Gets the value of the index property.
     *
     */
    public final int getIndex() {
        return index;
    }

    /**
     * Sets the value of the index property.
     *
     */
    public final void setIndex(int value) {
        this.index = value;
    }

    /**
     * Gets the value of the missing property.
     *
     */
    public final boolean isMissing() {
        return missing;
    }

    /**
     * Sets the value of the missing property.
     *
     */
    public final void setMissing(boolean value) {
        this.missing = value;
    }

    /**
     * Gets the value of the missingReason property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public final String getMissingReason() {
        return missingReason;
    }

    /**
     * Sets the value of the missingReason property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public final void setMissingReason(String value) {
        this.missingReason = value;
    }

    /**
     * Gets the value of the limitedModel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public final String getLimitedModel() {
        return limitedModel;
    }

    /**
     * Sets the value of the limitedModel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public final void setLimitedModel(String value) {
        this.limitedModel = value;
    }

}
