#!/bin/bash
#************************************************************************
# Copyright IBM Corp. 2016                                              *
# This file is part of Anomaly Detection Engine for Linux Logs (ADE).   *
#                                                                       *
# ADE is free software: you can redistribute it and/or modify           *
# it under the terms of the GNU General Public License as published by  *
# the Free Software Foundation, either version 3 of the License, or     *
# (at your option) any later version.                                   *
#                                                                       *
# ADE is distributed in the hope that it will be useful,                *
# but WITHOUT ANY WARRANTY; without even the implied warranty of        *
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         * 
# GNU General Public License for more details.                          *
#                                                                       *
# You should have received a copy of the GNU General Public License     *
# along with ADE.  If not, see <http://www.gnu.org/licenses/>.          *
#************************************************************************

# assumes this script is in <product_home>/bin directory
ADE_HOME=`dirname "$0"`/..

# set ADE_HOME to fully qualified path
ADE_HOME=`cd "$ADE_HOME" && pwd`
echo "ADE_HOME: $ADE_HOME"

# change to ADE_HOME dir because setup.props contains relative paths
eval "cd $ADE_HOME"

. bin/env.sh

$ADE_JAVA -cp $ADE_CLASSPATH -Dade.setUpFilePath=$ADE_SETUP_FILE $LOG_CMD_OPT org.openmainframe.ade.ext.main.ControlDB "$@"
