/*
 
    Copyright IBM Corp. 2012, 2016
    This file is part of Anomaly Detection Engine for Linux Logs (ADE).

    ADE is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ADE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with ADE.  If not, see <http://www.gnu.org/licenses/>.
 
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.19 at 11:50:56 PM IST 
//

package org.openmainframe.ade.impl.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java
 * content interface and Java element interface generated 
 * in the org.openmainframe.ade.impl.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Score_QNAME = new QName("", "Score");
    private final static QName _Attribute_QNAME = new QName("", "Attribute");
    private final static QName _AnalyzedInterval_QNAME = new QName("", "AnalyzedInterval");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.openmainframe.ade.impl.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ScoreType }
     * 
     */
    public ScoreType createScoreType() {
        return new ScoreType();
    }

    /**
     * Create an instance of {@link TimeLineType }
     * 
     */
    public TimeLineType createTimeLineType() {
        return new TimeLineType();
    }

    /**
     * Create an instance of {@link ActiveRulesType }
     * 
     */
    public ActiveRulesType createActiveRulesType() {
        return new ActiveRulesType();
    }

    /**
     * Create an instance of {@link ScoreSetType }
     * 
     */
    public ScoreSetType createScoreSetType() {
        return new ScoreSetType();
    }

    /**
     * Create an instance of {@link AnalyzedMessageSummaryType }
     * 
     */
    public AnalyzedMessageSummaryType createAnalyzedMessageSummaryType() {
        return new AnalyzedMessageSummaryType();
    }

    /**
     * Create an instance of {@link RuleType }
     * 
     */
    public RuleType createRuleType() {
        return new RuleType();
    }

    /**
     * Create an instance of {@link AnalyzedIntervalType }
     * 
     */
    public AnalyzedIntervalType createAnalyzedIntervalType() {
        return new AnalyzedIntervalType();
    }

    /**
     * Create an instance of {@link ScoreAttributeType }
     * 
     */
    public ScoreAttributeType createScoreAttributeType() {
        return new ScoreAttributeType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScoreType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Score")
    public JAXBElement<ScoreType> createScore(ScoreType value) {
        return new JAXBElement<>(_Score_QNAME, ScoreType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScoreAttributeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Attribute")
    public JAXBElement<ScoreAttributeType> createAttribute(ScoreAttributeType value) {
        return new JAXBElement<>(_Attribute_QNAME, ScoreAttributeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnalyzedIntervalType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AnalyzedInterval")
    public JAXBElement<AnalyzedIntervalType> createAnalyzedInterval(AnalyzedIntervalType value) {
        return new JAXBElement<>(_AnalyzedInterval_QNAME, AnalyzedIntervalType.class, null, value);
    }

    /**
     * Create an instance of {@link ModelNodeStatsType }
     * 
     */
    public ModelNodeStatsType createModelNodeStatsType() {
        return new ModelNodeStatsType();
    }

    /**
     * Create an instance of {@link ConfigurationResults }
     * 
     */
    public ConfigurationResults createConfigurationResults() {
        return new ConfigurationResults();
    }

    /**
     * Create an instance of {@link SingleConfigurationResult }
     * 
     */
    public SingleConfigurationResult createSingleConfigurationResult() {
        return new SingleConfigurationResult();
    }

}
