/*
 
    Copyright IBM Corp. 2012, 2016
    This file is part of Anomaly Detection Engine for Linux Logs (ADE).

    ADE is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ADE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with ADE.  If not, see <http://www.gnu.org/licenses/>.
 
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.06 at 02:54:13 PM IDT 
//

package org.openmainframe.ade.impl.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for SingleConfigurationResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SingleConfigurationResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AbnormalNode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AbnormalNodeValue" type="{}ModelNodeStatsType" minOccurs="0"/>
 *         &lt;element name="AnomalyType" type="{}AnomalyType"/>
 *         &lt;element name="AnomalyScore" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ModelNodeStats" type="{}ModelNodeStatsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SingleConfigurationResult", propOrder = {
        "abnormalNode",
        "abnormalNodeValue",
        "anomalyType",
        "anomalyScore",
        "modelNodeStats"
})
public class SingleConfigurationResult {

    @XmlElement(name = "AbnormalNode", required = true)
    protected String abnormalNode;
    @XmlElement(name = "AbnormalNodeValue")
    protected ModelNodeStatsType abnormalNodeValue;
    @XmlElement(name = "AnomalyType", required = true)
    protected AnomalyType anomalyType;
    @XmlElement(name = "AnomalyScore")
    protected double anomalyScore;
    @XmlElement(name = "ModelNodeStats")
    protected List<ModelNodeStatsType> modelNodeStats;

    /**
     * Gets the value of the abnormalNode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbnormalNode() {
        return abnormalNode;
    }

    /**
     * Sets the value of the abnormalNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbnormalNode(String value) {
        this.abnormalNode = value;
    }

    /**
     * Gets the value of the abnormalNodeValue property.
     * 
     * @return
     *     possible object is
     *     {@link ModelNodeStatsType }
     *     
     */
    public ModelNodeStatsType getAbnormalNodeValue() {
        return abnormalNodeValue;
    }

    /**
     * Sets the value of the abnormalNodeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModelNodeStatsType }
     *     
     */
    public void setAbnormalNodeValue(ModelNodeStatsType value) {
        this.abnormalNodeValue = value;
    }

    /**
     * Gets the value of the anomalyType property.
     * 
     * @return
     *     possible object is
     *     {@link AnomalyType }
     *     
     */
    public AnomalyType getAnomalyType() {
        return anomalyType;
    }

    /**
     * Sets the value of the anomalyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnomalyType }
     *     
     */
    public void setAnomalyType(AnomalyType value) {
        this.anomalyType = value;
    }

    /**
     * Gets the value of the anomalyScore property.
     * 
     */
    public double getAnomalyScore() {
        return anomalyScore;
    }

    /**
     * Sets the value of the anomalyScore property.
     * 
     */
    public void setAnomalyScore(double value) {
        this.anomalyScore = value;
    }

    /**
     * Gets the value of the modelNodeStats property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modelNodeStats property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModelNodeStats().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ModelNodeStatsType }
     * 
     * 
     */
    public List<ModelNodeStatsType> getModelNodeStats() {
        if (modelNodeStats == null) {
            modelNodeStats = new ArrayList<>();
        }
        return this.modelNodeStats;
    }

}
