/*
 
    Copyright IBM Corp. 2012, 2016
    This file is part of Anomaly Detection Engine for Linux Logs (ADE).

    ADE is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ADE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with ADE.  If not, see <http://www.gnu.org/licenses/>.
 
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.06 at 05:15:48 PM IDT 
//

package org.openmainframe.ade.impl.flow.factory.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for AnalysisGroupFlowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnalysisGroupFlowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UploadFramingFlow" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TrainingIntervalFactor" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AnalysisFramingFlow" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ScoringSchema" type="{http://flow.impl.ade.openmainframe.org/factory}ScoringSchemaType" maxOccurs="unbounded"/>
 *         &lt;element name="Outputer" type="{http://flow.impl.ade.openmainframe.org/factory}OutputerType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FinalAnomalyMessageScorer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FinalAnomalyIntervalScorer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnalysisGroupFlowType", namespace = "http://flow.impl.ade.openmainframe.org/factory", propOrder = {
        "uploadFramingFlow",
        "trainingIntervalFactor",
        "analysisFramingFlow",
        "scoringSchema",
        "outputer",
        "finalAnomalyMessageScorer",
        "finalAnomalyIntervalScorer"
})
public class AnalysisGroupFlowType {

    @XmlElement(name = "UploadFramingFlow")
    protected String uploadFramingFlow;
    @XmlElement(name = "TrainingIntervalFactor")
    protected Integer trainingIntervalFactor;
    @XmlElement(name = "AnalysisFramingFlow")
    protected String analysisFramingFlow;
    @XmlElement(name = "ScoringSchema", required = true)
    protected List<ScoringSchemaType> scoringSchema;
    @XmlElement(name = "Outputer")
    protected List<OutputerType> outputer;
    @XmlElement(name = "FinalAnomalyMessageScorer", required = true)
    protected String finalAnomalyMessageScorer;
    @XmlElement(name = "FinalAnomalyIntervalScorer")
    protected String finalAnomalyIntervalScorer;
    @XmlAttribute(required = true)
    protected String name;

    /**
     * Gets the value of the uploadFramingFlow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUploadFramingFlow() {
        return uploadFramingFlow;
    }

    /**
     * Sets the value of the uploadFramingFlow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUploadFramingFlow(String value) {
        this.uploadFramingFlow = value;
    }

    /**
     * Gets the value of the trainingIntervalFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTrainingIntervalFactor() {
        return trainingIntervalFactor;
    }

    /**
     * Sets the value of the trainingIntervalFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTrainingIntervalFactor(Integer value) {
        this.trainingIntervalFactor = value;
    }

    /**
     * Gets the value of the analysisFramingFlow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnalysisFramingFlow() {
        return analysisFramingFlow;
    }

    /**
     * Sets the value of the analysisFramingFlow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnalysisFramingFlow(String value) {
        this.analysisFramingFlow = value;
    }

    /**
     * Gets the value of the scoringSchema property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the scoringSchema property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScoringSchema().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScoringSchemaType }
     * 
     * 
     */
    public List<ScoringSchemaType> getScoringSchema() {
        if (scoringSchema == null) {
            scoringSchema = new ArrayList<>();
        }
        return this.scoringSchema;
    }

    /**
     * Gets the value of the outputer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outputer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutputer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutputerType }
     * 
     * 
     */
    public List<OutputerType> getOutputer() {
        if (outputer == null) {
            outputer = new ArrayList<>();
        }
        return this.outputer;
    }

    /**
     * Gets the value of the finalAnomalyMessageScorer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalAnomalyMessageScorer() {
        return finalAnomalyMessageScorer;
    }

    /**
     * Sets the value of the finalAnomalyMessageScorer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalAnomalyMessageScorer(String value) {
        this.finalAnomalyMessageScorer = value;
    }

    /**
     * Gets the value of the finalAnomalyIntervalScorer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinalAnomalyIntervalScorer() {
        return finalAnomalyIntervalScorer;
    }

    /**
     * Sets the value of the finalAnomalyIntervalScorer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinalAnomalyIntervalScorer(String value) {
        this.finalAnomalyIntervalScorer = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
