/*
 
    Copyright IBM Corp. 2012, 2016
    This file is part of Anomaly Detection Engine for Linux Logs (ADE).

    ADE is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ADE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with ADE.  If not, see <http://www.gnu.org/licenses/>.
 
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.06 at 05:15:48 PM IDT 
//

package org.openmainframe.ade.impl.flow.factory.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for FramingFlowType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FramingFlowType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FramerClass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FramerProperty" type="{http://flow.impl.ade.openmainframe.org/factory}PropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="databaseId" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="duration" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="consecutive" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FramingFlowType", namespace = "http://flow.impl.ade.openmainframe.org/factory", propOrder = {
        "framerClass",
        "framerProperty"
})
public class FramingFlowType {

    @XmlElement(name = "FramerClass", required = true)
    protected String framerClass;
    @XmlElement(name = "FramerProperty")
    protected List<PropertyType> framerProperty;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected int databaseId;
    @XmlAttribute(required = true)
    protected long duration;
    @XmlAttribute(required = true)
    protected boolean consecutive;

    /**
     * Gets the value of the framerClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFramerClass() {
        return framerClass;
    }

    /**
     * Sets the value of the framerClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFramerClass(String value) {
        this.framerClass = value;
    }

    /**
     * Gets the value of the framerProperty property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the framerProperty property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFramerProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType }
     * 
     * 
     */
    public List<PropertyType> getFramerProperty() {
        if (framerProperty == null) {
            framerProperty = new ArrayList<>();
        }
        return this.framerProperty;
    }
    
    /**
     * Returns the value of a property type given a specified key.
     * @param key The key value of the property to be obtained.
     * @return The value of the property
     */
    public String getPropertyByKey(String key){
        String property = null;
        if (framerProperty == null){
            return property;
        }
        for (PropertyType propertyType : framerProperty){
            if (propertyType.getKey().equals(key)){
                property = propertyType.getValue();
                break;
            }
        }
        return property;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the databaseId property.
     * 
     */
    public int getDatabaseId() {
        return databaseId;
    }

    /**
     * Sets the value of the databaseId property.
     * 
     */
    public void setDatabaseId(int value) {
        this.databaseId = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     */
    public long getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     */
    public void setDuration(long value) {
        this.duration = value;
    }

    /**
     * Gets the value of the consecutive property.
     * 
     */
    public boolean isConsecutive() {
        return consecutive;
    }

    /**
     * Sets the value of the consecutive property.
     * 
     */
    public void setConsecutive(boolean value) {
        this.consecutive = value;
    }

}
