/*
 
    Copyright IBM Corp. 2012, 2016
    This file is part of Anomaly Detection Engine for Linux Logs (ADE).

    ADE is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ADE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with ADE.  If not, see <http://www.gnu.org/licenses/>.
 
*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.06 at 05:15:48 PM IDT 
//

package org.openmainframe.ade.impl.flow.factory.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for LayoutType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LayoutType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FramingFlow" type="{http://flow.impl.ade.openmainframe.org/factory}FramingFlowType" maxOccurs="unbounded"/>
 *         &lt;element name="AnalysisGroupFlow" type="{http://flow.impl.ade.openmainframe.org/factory}AnalysisGroupFlowType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LayoutType", namespace = "http://flow.impl.ade.openmainframe.org/factory", propOrder = {
        "framingFlow",
        "analysisGroupFlow"
})
public class LayoutType {

    @XmlElement(name = "FramingFlow", required = true)
    protected List<FramingFlowType> framingFlow;
    @XmlElement(name = "AnalysisGroupFlow", required = true)
    protected List<AnalysisGroupFlowType> analysisGroupFlow;

    /**
     * Gets the value of the framingFlow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the framingFlow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFramingFlow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FramingFlowType }
     * 
     * 
     */
    public List<FramingFlowType> getFramingFlow() {
        if (framingFlow == null) {
            framingFlow = new ArrayList<FramingFlowType>();
        }
        return this.framingFlow;
    }

    /**
     * Gets the value of the analysisGroupFlow property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the analysisGroupFlow property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnalysisGroupFlow().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AnalysisGroupFlowType }
     * 
     * 
     */
    public List<AnalysisGroupFlowType> getAnalysisGroupFlow() {
        if (analysisGroupFlow == null) {
            analysisGroupFlow = new ArrayList<AnalysisGroupFlowType>();
        }
        return this.analysisGroupFlow;
    }

}
